#!/bin/bash

consul_url="https://monconsul.intra"
consul_prefix="devs"
consul_token="votre_token"  # Remplacez par votre token Consul

# Récupérer la liste des clés sous le préfixe
keys=$(curl -s -H "Authorization: Bearer $consul_token" "$consul_url/v1/kv/$consul_prefix?keys")

# Parcourir les clés
for key in $keys; do
  # Récupérer les données JSON associées à la clé
  data=$(curl -s -H "Authorization: Bearer $consul_token" "$consul_url/v1/kv$key")
  
  # Extraire les valeurs des clés "ssh_port_socat" et "dev_hostname" (à adapter selon votre structure JSON)
  listen_port=$(echo "$data" | jq -r '.[0].Value' | base64 -d | jq -r '.ssh_port_socat')
  remote_server=$(echo "$data" | jq -r '.[0].Value' | base64 -d | jq -r '.dev_hostname')
  
  if [[ -n "$listen_port" && -n "$remote_server" ]]; then
    # Construire la commande socat
    socat_cmd="socat TCP-LISTEN:$listen_port,fork,reuseaddr TCP:$remote_server:22"
    
    # Exécuter la commande socat en arrière-plan
    $socat_cmd &
    
    echo "Commande socat exécutée pour le port $listen_port vers $remote_server"
  fi
done
